### ISSUE TITLE
Possible to use this with yi dome 1080p camera ?

### ISSUE THREAD

**Issue by gelsas** [npetrovski/yi-hack-easy#4]
Is it Possible to use this with yi dome 1080p camera ?

**Comment by npetrovski** [comment]
Unfortunately no, for 1080p the storage partitioning is made differently and the firmware wont install properly.

**Comment by gelsas** [comment]
Oh :( I was hoping for the possiblity for an RTSP server for my camera.

Thank you for the quick answer!

**Comment by npetrovski** [comment]
No problem.

**Comment by Aceman53** [comment]
> Is it Possible to use this with yi dome 1080p camera ?

Hi Gelsas, I haven't found a way to send a private message to Gethub User, so I'm adding a comment to your Issue/Question. If you know how, please let me know.
I have a  yi dome 720p HD camera. I was wondering if you came across anything useful for your yi dome 1080p cam? I'm new to github, so i'm not sure of the best way to find things. I came across this via keyword search 'YI*'. I'm also looking for a hack that will allow ACCESS/CONTROL/VIEWING/SMART of two different Cam manufactures, YI and WAYZ CAM v2 (1080p). If you know of any Discussion/Boards/Communities/Forums I'd appreciate the info.  
Thanks in advance, **Aceman53**
